name: transee
version: 0.0.1
description: App for tracking public transport
author: Michael Zhukov <zhukovme@gmail.com>

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
